### ISSUE TITLE
Not able to integrate Report Portal with Karate Framework(API testing) 

### ISSUE THREAD

**Issue by PoornimaGopalan** [reportportal/agent-java-karate#10]
We are not able to integrate Report Portal with Karate Framework(API testing).
Please suggest options to make it feasible

Note: We have also tried with the below dependency with cucumber but no luck since the runner class is karate (Karate.class) and hence we need options to integrate karate with report portal

<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>agent-java-cucumber</artifactId>
  <version>4.0.0</version>
</dependency>

**Comment by DzmitryHumianiuk** [comment]
@Tejareddy1 @yhthahira 
take a look into 
https://github.com/reportportal/agent-java-karate/pull/9

**Comment by evgenytkachenko** [comment]
@DzmitryHumianiuk  the new implementation requires to have a release version of agent-java-karate. Do you plan to have it soon?

**Comment by DzmitryHumianiuk** [comment]
@evgenytkachenko yes.
It’s in @HardNorth roadmap

**Comment by yhthahira** [comment]
@DzmitryHumianiuk DzmitryHumianiuk
Can you please provide the exact location?

**Comment by DzmitryHumianiuk** [comment]
@yhthahira you asking for roadmap location?
it's in closed jira instance.

as for now, you can pull code from this PR
https://github.com/reportportal/agent-java-karate/pull/9

**Comment by HardNorth** [comment]
Please use the latest official Agent version and setup reporting according to documentation to address the issue:
https://github.com/reportportal/agent-java-karate/releases/tag/5.0.0
https://github.com/reportportal/agent-java-karate/blob/develop/README.md
