### ISSUE TITLE
Report portal not working with Karate 1.0.1

### ISSUE THREAD

**Issue by deepsmittal** [reportportal/agent-java-karate#14]
When i tried using the code , it is not pushing any details to report portal. However when i tried in another framework it worked fine. It would be great help if you could share the steps on how to integrate report portal with Karate 1.0.1 .

thanks in advance.

**Comment by kirksl** [comment]
@deepsmittal maybe our solution can help you?
https://github.com/kirksl/karate-maven-gradle

**Comment by HardNorth** [comment]
Please use the latest official Agent version and setup reporting according to documentation to address the issue:
https://github.com/reportportal/agent-java-karate/releases/tag/5.0.0
https://github.com/reportportal/agent-java-karate/blob/develop/README.md
