### ISSUE TITLE
Sending Attachments with Karate1.0.1  with Report Portal  (Using https://github.com/kirksl/karate-maven-gradle )

### ISSUE THREAD

**Issue by Shivin89** [reportportal/agent-java-karate#15]
Hi Report Portal,
I wanted to use the report Portal with Karate tool and the integration that is on GitHub is pretty old with the new version of Karate 1.0.1, but I found custom-written Integration with the new version of Karate and it works well.
In that custom version “Attachments aren’t been sent to Report Portal ” My question here is Can we get support How to send Attachments to Report Portal via Karate Integration?
Custom Code for Karate Integration: https://github.com/kirksl/karate-maven-gradle
I have raised an issue there but wanted here support too If there is a way to send attachments

**Comment by HardNorth** [comment]
@Shivin89 How are you going to log these attachments? Please point on Karate documentation / example for better understanding.

**Comment by HardNorth** [comment]
Abandoned
