### ISSUE TITLE
Add logging to publishing process

### ISSUE THREAD

**Issue by melsumadiAH** [reportportal/agent-java-karate#20]
**Is your feature request related to a problem? Please describe.**
It is difficult to tell what part of the process ReportPortal is currently on.
For example if it is missing UUID , there is no feedback that a uuid is missing. The lib will just fail quietly.

**Describe the solution you'd like**
Add logs which appear in the pipeline that communicate the current activity and the progress.
eg.
 * ReportPortal  has launched
 * ReportPortal is searching for test results
 * ReportPortal is missing UUID
 * ReportPortal 401 error
 * ReportPortal has posted successfully 
 * etc

**Comment by HardNorth** [comment]
Please use the latest official Agent version and setup logging according to documentation to address the issue:
https://github.com/reportportal/agent-java-karate/releases/tag/5.0.0
https://github.com/reportportal/agent-java-karate/blob/develop/README.md
