### ISSUE TITLE
How to use karate-config.js file with agent-java-karate project

### ISSUE THREAD

**Issue by RG108** [reportportal/agent-java-karate#5]
Please note that I installed all the RP dependencies and scripts are working fine.
Thanks for that.
I had another inquiry which is that karate-config.js file is not getting read by the sample project.
I put URL reference of the services in karate-config.js which I am calling through feature file like this
Scenario: create access token
Given url oauth1 + '.uk' + oauth2
And path '/token'
And form field client_id = '***'
And form field client_secret = ''
And form field grant_type = ''
When method post
Then status 200
Where oauth1 & oauth2 are the config value which are present in karate-config.js file.

While running the project I am getting below error:
�[31mjava.lang.RuntimeException: javascript evaluation failed: oauth1 + '.uk' + oauth2
Kindly suggest !

**Comment by RG108** [comment]
Hi @filland , @rahul267 ,
Could you tell me please when we can have report portal agent-java-karate latest version?
As the karate has 0.9.2 release which is not compatible with the agent due to that the above issue appeared.

**Comment by HardNorth** [comment]
@RG108 I don't believe that it's something related to ReportPortal and Karate integration for ReportPortal. Please address this question to corresponding community, E.G. Karate.
