### ISSUE TITLE
Compilation errors with latest karate versions

### ISSUE THREAD

**Issue by deepak-monotype** [reportportal/agent-java-karate#7]
The project is not compiling when using Karate version 0.9.3.

**Comment by mosqueik** [comment]
Yes, from 0.9.3 there are a lot of changes in Karate and the project is not compiling, could you please update the class @DzmitryHumianiuk thanks !

**Comment by DzmitryHumianiuk** [comment]
@mosqueik feel free to send Pull Request

**Comment by evgenytkachenko** [comment]
Any updates?

**Comment by DzmitryHumianiuk** [comment]
@evgenytkachenko @HardNorth is not duty, will take a look according to priorities.

**Comment by karthikbits** [comment]
Hi have developed a new report portal karate plugin https://github.com/karthikbits/reportportal-karate . This uses the latest event enhanced events framework in Karate. It needs 0.9.5.RC3. Doing some testing within my company.

**Comment by HardNorth** [comment]
Please use karate of version 1.3.1 and newer. Earlier versions of Karate are not planned for support.

To use Karate with ReportPortal add the latest official Agent version and setup reporting according to documentation to address the issue:
https://github.com/reportportal/agent-java-karate/releases/tag/5.0.0
https://github.com/reportportal/agent-java-karate/blob/develop/README.md
