### ISSUE TITLE
karate version 0.9.3 not working with reportPortal

### ISSUE THREAD

**Issue by guptapranay** [reportportal/agent-java-karate#8]
Team,
 For karate 0.9.3, reportPortalIo is not working. Could you please let us know, how to resolve this?

**Comment by supadhyaywebuy** [comment]
@guptapranay  did you got resolution for compatibility issue?

**Comment by DzmitryHumianiuk** [comment]
@guptapranay any details?

**Comment by guptapranay** [comment]
Hi @DzmitryHumianiuk @supadhyaywebuy 

No, I still have this issue. Downgrading karate to 0.7.0 works well with agent-java-karate. But with higher versions, it fails.

**Comment by DzmitryHumianiuk** [comment]
@Yumfriez @HardNorth can you please take a look?

**Comment by karthikbits** [comment]
Hi have developed a new report portal karate plugin https://github.com/karthikbits/reportportal-karate . This uses the latest event enhanced events framework in Karate. It needs 0.9.5.RC3. Doing some testing within my company.

**Comment by guptapranay** [comment]
@Yumfriez any updates? Or @karthikbits is your the official one?

**Comment by workwithprashant** [comment]
> Hi have developed a new report portal karate plugin https://github.com/karthikbits/reportportal-karate . This uses the latest event enhanced events framework in Karate. It needs 0.9.5.RC3. Doing some testing within my company.

@karthikbits Were you able to make it work with karate 0.9.5.RC5 ?

**Comment by DzmitryHumianiuk** [comment]
@workwithprashant does 0.9.5RC5 compatible with 0.9.4?
Or it has braking change as well?

**Comment by workwithprashant** [comment]
@DzmitryHumianiuk 0.9.5.RC5 is not compatible with 0.9.4. I have made few code changes to https://github.com/karthikbits/reportportal-karate to make it work properly with 0.9.5.RC5 except that scenario steps does display in order on ReportPortal.

**Comment by karthikbits** [comment]
Can u please raise a pull request to merge our changes.
Thanks,Karthik
    On Saturday, 8 February, 2020, 10:11:45 pm IST, workwithprashant <notifications@github.com> wrote:  
 
 
@DzmitryHumianiuk 0.9.5.RC5 is not compatible with 0.9.4. I have made few code changes to https://github.com/karthikbits/reportportal-karate to make it work properly with 0.9.5.RC5 except that scenario steps does display in order on ReportPortal.

**Comment by DzmitryHumianiuk** [comment]
Well,
before it merged - it should be tested and verified.
my main concern is that active version changes so quick and each new version is not backward compatible with previous.

and still, they have `Release Candidate` label, which not guarantee it stability.
At the moment, we have requests to make it work with 0.9.3, 0.9.4 and now with 0.9.5

it's a huge overhead to keep it stable and release new packages each time, when new RC or 0.9.xxxx version will be avaialble.

In general,
are there any public roadmap regarding 1.0.0 stable version of karate available?

**Comment by evgenytkachenko** [comment]
@karthikbits do you have examples of how you use karate-agent you have built?
I mean how to use it in the Test Runner ?

**Comment by evgenytkachenko** [comment]
@workwithprashant did you make it work with 0.9.5 properly?

**Comment by evgenytkachenko** [comment]
@workwithprashant @karthikbits how did you make https://github.com/karthikbits/reportportal-karate work with 0.9.5 ?

**Comment by workwithprashant** [comment]
@evgenytkachenko I had to use client-java to make it work with Karate 0.9.5. It will be nice if we can have agent working for Karate since I have to keep updating client-java implementation for every new feature Reportportal releases.

**Comment by anilsky** [comment]
@karthikbits .. may I know the reason behind for your responsiveness? i am looking forward for the solution to the same (RP integration with Karate 0.9.5) .. thanks in advance

**Comment by anilsky** [comment]
> @evgenytkachenko I had to use client-java to make it work with Karate 0.9.5. It will be nice if we can have agent working for Karate since I have to keep updating client-java implementation for every new feature Reportportal releases.

@workwithprashant do you have an example to share please ?

**Comment by anilsky** [comment]
@workwithprashant can you please share how did you integrate 0.9.5 with RP using client-java ?
(gradle or maven ?)

**Comment by anilsky** [comment]
@DzmitryHumianiuk @workwithprashant 
We have used @workwithprashant solution to integrate RP with Karate 0.9.5 and it would be beneficial for wider community if this can be reviewed and merged to master 
much appreciated

**Comment by kirksl** [comment]
@DzmitryHumianiuk @workwithprashant appreciate it if i can work with you to determine and solve all issues with this integration.  can you help me understand what the remaining issues are.  @workwithprashant are you planning on submitting your changes to support 0.9.6+ into this repo?  i'd also like to understand why the integration keeps breaking, create a specific list of the problems and see if we can create a level of harmony between Karate and ReportPortal projects.  i'd be happy to facilitate resolution of issues within the Karate project.

**Comment by kirksl** [comment]
@DzmitryHumianiuk @workwithprashant i believe the reason for instability has been with the method of implementation to integrate RP to Karate.  i haven't had the time to create a clean abstration with ReportPortalAppender however i have implemented a solution below which should prove to be robust.  possibly this could be insightful for a ReportPortalAppender solution in the future.
https://github.com/kirksl/karate-maven-gradle

**Comment by HardNorth** [comment]
Please use karate of version 1.3.1 and newer. Earlier versions of Karate are not planned for support.

To use Karate with ReportPortal add the latest official Agent version and setup reporting according to documentation to address the issue:
https://github.com/reportportal/agent-java-karate/releases/tag/5.0.0
https://github.com/reportportal/agent-java-karate/blob/develop/README.md
